document:
  name: Linee guida per la classificazione di prodotti e servizi digitali, processi e modelli di gestione
  description:
      Le linee guida 4 individuano e descrivono le diverse tassonomie e mappature di processi e servizi menzionate nel Piano nazionale di digitalizzazione del patrimonio culturale (PND), al fine di ordinare i differenti concetti per tipologie “di senso” e orientare il lettore.
  tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
